import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#8257e5",
  },
  headerContainer: {
    paddingTop: 30,
    backgroundColor: "#774DD6",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 5,
    borderWidth: 1,
    borderColor: "#6842C2",
  },
  headerText: {
    marginLeft: 20,
    color: "#D4C2FF",
    fontSize: 14,
    lineHeight: 15,
    textAlign: "center",
    fontFamily: "Archivo_600SemiBold",
  },
  topContainer: {
    flex: 1,
    justifyContent: "center",
    paddingTop: 20,
    paddingBottom: 40,
  },
  banner: {
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    width: "100%",
  },
  profileImg: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 10,
  },
  profileName: {
    color: "#FFFFFF",
    fontFamily: "Archivo_700Bold",
    fontSize: 24,
    lineHeight: 25,
  },
  profileSubject: {
    color: "#D4C2FF",
    fontFamily: "Poppins_400Regular",
    fontSize: 16,
    lineHeight: 26,
  },
  bottomContainer: {
    flex: 2,
    backgroundColor: "#E5E5E5",
    paddingHorizontal: 15,
    paddingBottom: 15,
  },
  profileDataContainer: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E6E6F0",
    borderRadius: 8,
    padding: 20,
    paddingTop: 15,
    marginTop: -25,
    flexDirection: "column",
  },
  profileTitle: {
    color: "#32264D",
    fontFamily: "Archivo_600SemiBold",
    fontSize: 20,
    lineHeight: 30,
  },
  lineSeparator: {
    marginVertical: 5,
    borderBottomColor: "#E6E6F0",
    borderBottomWidth: 1,
  },
  lineSeparatorRed: {
    borderBottomColor: "red",
    borderBottomWidth: 1,
    marginBottom: 10,
  },
  dataLabel: {
    color: "#9C98A6",
    fontFamily: "Poppins_400Regular",
    fontSize: 12,
    lineHeight: 22,
    marginBottom: 5,
  },
  dataInput: {
    backgroundColor: "#FAFAFC",
    padding: 10,
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: "#E6E6F0",
    borderRadius: 8,
    color: "#6A6180",
    fontSize: 14,
    lineHeight: 24,
    marginBottom: 15,
  },
  timeAvailable: {},
  timeAvailableTitle: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  newTime: {
    alignItems: "center",
    color: "#8257E5",
    fontSize: 14,
    lineHeight: 26,
    fontFamily: "Archivo_600SemiBold",
  },
  deleteTime: {
    alignItems: "center",
    color: "red",
    fontSize: 14,
    lineHeight: 26,
    fontFamily: "Archivo_600SemiBold",
  },
  hoursSelectTitle: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 5,
  },
  hoursSelectContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  hourInputContainer: {
    backgroundColor: "#FAFAFC",
    padding: 10,
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: "#E6E6F0",
    borderRadius: 8,
    color: "#6A6180",
    fontSize: 14,
    lineHeight: 24,
    marginBottom: 15,
    width: '48%',
  },
  buttonContainer: {
    marginTop: 20,
  },
  loginButton: {
    backgroundColor: "#04D361",
    borderRadius: 8,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
  },
  loginButtonText: {
    color: "#FFFFFF",
    fontFamily: "Archivo_600SemiBold",
    fontSize: 16,
    lineHeight: 26,
  },
});

export default styles;
